---
application:
  name: "chashi-frontend"
  project: "chashi"
  organization: "QoveryCommunity"
routers:
- name: "main-chashi-frontend"
  routes:
  - application_name: "chashi-frontend"
    paths:
    - "/*"
